ufbx_math: Use NEON instead of SSE on ARM64EC
Thanks MSVC.. xmmintrin.h(31,1): error C1189: #error:  this header should only be included through <intrin.h>